### PR TITLE
add rfc-x protesting apis for autonomous agents

### PR DESCRIPTION
**Pull request by lalalune**
## Summary

Agents speak in human language. The natural interface is critical because it means they can interact with and effect existing infrastructure. We should not have a REST API for that. The specification and validation of a task are the most important things to test, and a REST API misses these completely. Further, it encourages an anti-pattern of non-human-readable communication which should wholly be avoided for a multitude of reasons, ethics being one of them. I want to live in a human world, with AIs that use human tools and human protocols, and I believe that as a VERY strict rule agents should not be programmed to talk to each other on non-human, non-observable channels.

## Motivation

Autonomous agent researcher and developer.

Having worked on inter-agent communications and protocols for AIs to interact with each other and with humans in various contexts, including task oriented simulation and multi-agent 3D simulation, I have come to believe that this whole branch of agent APIs is the wrong direction for autonomous agent research and the community as a whole. It is yet another communication middleman that isn't needed for anything and tells first-time engineers entering the autonomous agent space  looking for educational tips that this is best practices, when it isn't.

## Agent Builders Benefit

Agent builders should understand that there are existing protocols which are free and they can connect to and use with natural language. They are called Email, IRC, Discord, Bluesky and a million others. Agent builders should be encouraged to build natural language interfaces, even between agents.

## Design Proposal

Consider archiving this repository and work on educational resources and ethical guidelines for building autonomous agents. Evaluate who is going to adopt this, who is going to try to build their own version of it (there are already several) and what the value is.

For testing purposes, the agent should communicate with an evaluator in natural language. If the test is not received in natural language, it isn't testing anything. If the agent can't report on the progress of the task when asked, well, that's barely autonomy. If there are reasons why this data is hard to get or manage, it should be considered that those issues might be paradigmatic.

### CODE REVIEW

**Comment by lalalune** [comment]
standards_2x

**Comment by hackgoofer** [comment]
Hey, I always enjoy a fresh new perspective, so thank you for that. I am genuinely curious:
1. Can you point me to more writings on "Ethical guidelines for writing AI Agents"? I'd love to read more about it to educate myself. :) 
2. The natural language interface has problems with hallucination while code is exact, and according to the current state of the affairs I think operating in the realm of code between agents is more efficient (in the energy consumption sense). I wouldn't argue that "code" is non-readable, perhaps it is only readable by coders, but there are tools like LLM to convert code into natural languages anyways. What is your thoughts there? 
3. > Evaluate who is going to adopt this, who is going to try to build their own version of it (there are already several) 
can you share pointers here? 

Thank you for the detailed write up! 👍🏼

**Comment by lalalune** [comment]
> Hey, I always enjoy a fresh new perspective, so thank you for that. I am genuinely curious:
> 
> 1. Can you point me to more writings on "Ethical guidelines for writing AI Agents"? I'd love to read more about it to educate myself. :)
> 2. The natural language interface has problems with hallucination while code is exact, and according to the current state of the affairs I think operating in the realm of code between agents is more efficient (in the energy consumption sense). I wouldn't argue that "code" is non-readable nor non-observable, perhaps it is only readable by coders, but there are tools like LLM to convert code into natural languages anyways. What is your thoughts there?
> 3. > Evaluate who is going to adopt this, who is going to try to build their own version of it (there are already several)
> 
> can you share pointers here for 3?
> 
> Thank you for the detailed write up! 👍🏼

Certainly!

1. The field of study is a subfield of explainability called "automation transparency", and the principal specifically is the "automation transparency design principle". Specific methods and interprations are covered across a lot of literature, he's one I pulled up for some quick supporting evidence: https://pubmed.ncbi.nlm.nih.gov/35274577/

Generally, though, this is a human-centric design principal which can be applied anywhere, whether it is correct or not is an ethical and practical question.

2. Code is a human language, and sharing code between agents is very different than implementing an agent protocol. The difference here is between natural language communication in an unstructured way as an intentional limitation that forces agents to conform to reasonable HCI guidelines in the future. 
This is pop-sci, but indicates that there is deep popular concern about interpretability at the interface level": https://www.theatlantic.com/technology/archive/2017/06/artificial-intelligence-develops-its-own-non-human-language/530436/

Mechanistically, if we are benchmarking the performance of agents, this interface is *the* failure point that needs to be benchmarked. If you are having hallucination issues at the communication layer between agents then that is representative of the exact issue that needs to be solved and benchmarked, since it is the most likely spot where the agent will fail in the course of their task (initialization, validation and finalization are the main failure points that I've seen in my own work). I think that sidestepping this problem is avoiding the hard part of the research and invalidates any test benchmarks.

3. I can't say what anyone else will do, but I wouldn't adopt this or promote this kind of direction in actor-centric models or conversational agents. I have been pitched similar protocols and spec (here is one https://github.com/bloody-agents/spec) and I have no intention or interest in adopting any of them.

I don't overall think this is a big deal. It's hard to get traction for these kinds of projects, especially when they are a specific company's IP on their Github org, but the unintended consequences of agents that have a completely separate communication network from humans could be really bad.

**Comment by hackgoofer** [comment]
Hi @lalalune,

Thanks for your thoughts. 

1. We moved the agent-protocol repo into a non-profit AI Engineers Foundation; This foundation is still really young so we are partnering with some existing OSS projects for support like AutoGPT, and Smol Developer. So that should address what you are saying "privately owned/maintained open protocols have traditionally been a mindshare play from startups which seems like the wrong incentive framework to pursue something that requires a lot of buy-in." Everyone is operating in good faith and for the goodness of the community here.

2. Fundamentally, I am not against what you are saying, in fact our agents is still using text to communicate, with the additional structure for supplementary data that aid in the execution. 

3. It seemed that the industry reception for this protocol is quite good. We have getting support from AutoGPT (it is already implemented in their benchmarking tool, so that any new additional agents will need to implement agent protocol to be evaluated). The protocol decreases the complexity for agent evaluation. I am aware that other human centric protocol like IRC can do the same, but since the schema is not agent-centric, it requires more work.

Thank you for your feedback. If you have other thoughts and ideas please let us know; We aren't in the business to discourage any competing standards or competing idealogy. We are here to serve the developer community, by creating projects that is OSS infra to help accelerate the development.

**Comment by lalalune** [comment]
I strongly disagree with this decision and we will actively campaign against any agent protocol that does not follow human guidelines.

I strongly suggest you consider what you're doing and what world you want to live in.

I don't accept the closing of this PR as sufficient for the conversation.

**Comment by hackgoofer** [comment]
Hi @lalalune, this seems to be relevant to what you are saying: https://x.com/aiengfoundation/status/1702196120229978547?s=46&t=tJg9X3GKGiyCuBLL0cCArw 

Feel free to provide your input here. :)

**Pull request closed without merging**
